username = input("Введите имя пользователя: ")
title = input("Введите название заметки: ")
content = input("Введите текст заметки: ")
status = input("Введите статус заметки: ")
created_date = input("Введите дату создания заметки: ")
issue_date = input("Введите дедлайн заметки: ")

print("Имя пользователя:", username)
print("Название заметки:", title)
print("Описание заметки:", content)
print("Статус заметки:", status)
print("Дата создания заметки:", str(created_date))
print("Дедлайн заметки:", str(issue_date))
